### ISSUE TITLE
Clicking "Login" with no credentials allows access to an account

### ISSUE THREAD

**Issue by alizameller** [CooperExchange/UI#13]
This might be leftover from when the user_id was hard coded in -- lets look into this

**Comment by EvanKluger** [comment]
This wasn't the issue. The reason why it was logging in was because user_id = 3 has a username and password equal to nothing. 
To solve this we need to do 2 things, When registering for an account we need to make sure a user cannot register for an account with blank values for username and password. When updating account settings same thing.

**Comment by EvanKluger** [comment]
Issue solved.
